### PR TITLE
Added dependency

### PR DESCRIPTION
**Pull request by nelsonvarela**
I've added requests as required install/dependency. Maybe there is a reason why requests was not added as dependency in the first place? A reason could be to not interfere with the requests version used in the same project as the one where the Mollie client is being/going to be used.

If no reason for this, I'd like this pull request to be merged into master.

### CODE REVIEW

**Comment by nelsonvarela** [comment]
Someone?

**Comment by RickWong** [comment]
Thanks @nelsonvarela

**Comment by nelsonvarela** [comment]
Can someone please accept this! 2 new versions where released after this issue.

**Comment by Daanvm** [comment]
Hi @nelsonvarela, thanks for the pull request and sorry for the delay!

**Pull request merged**
