### PR TITLE
Adding urllib3 as dependency

### PR DESCRIPTION
**Pull request by jacopsd**

### CODE REVIEW

**Comment by whyscream** [comment]
Hi @jacopsd , urllib3 should be pulled in as a dependency for requests already. I agree that it's better to explicitly list it as a dependency, but I'm curious why you opened the PR. Did you run into problems?

**Comment by jacopsd** [comment]
Dear Tom

Not a big “problem”, but my web application failed to start after upgrading the Mollie package.

Regards
Davy

**Comment by whyscream** [comment]
> but my web application failed to start after upgrading the Mollie package.

What was the error that was displayed during the failure?
Could you show me the output of `pip freeze` in the actual environment of your application?

**Comment by jacopsd** [comment]
Tom

The -as expected-  error is:


 474 2020-12-04 12:50:20,749:   File "./swingit/online_payments.py", line 2, in <module>
 475 2020-12-04 12:50:20,749:     from mollie.api.client import Client
 476 2020-12-04 12:50:20,749: 
 477 2020-12-04 12:50:20,749:   File "/home/davy/.virtualenvs/EXP3.6/lib/python3.6/site-packages/mollie/api/client.py", line 10, in <module>
 478 2020-12-04 12:50:20,749:     from urllib3.util import Retry
 479 2020-12-04 12:50:21,849: Error running WSGI application
 480 2020-12-04 12:50:21,850: ModuleNotFoundError: No module named 'urllib3'
 481 2020-12-04 12:50:21,851:   File "/home/davy/.virtualenvs/EXP3.6/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call
 482 2020-12-04 12:50:21,851:     response = self.get_response(request)



> On 7 Dec 2020, at 11:15, Tom Hendrikx <notifications@github.com> wrote:
> 
> 
> but my web application failed to start after upgrading the Mollie package.
> 
> What was the error that was displayed during the failure?
> Could you show me the output of pip freeze in the actual environment of your application?
> 
> 


This output of this command is very big since we use many packages, and not really relevant for this issue I believe.
Urllib3 was the only missing dependency.

**Comment by whyscream** [comment]
> This output of this command is very big since we use many packages, and not really relevant for this issue I believe.
> Urllib3 was the only missing dependency.

I'm mainly interested in the `requests` version that you're using. It should pull in the urllib3 dependency since v2.16.0 (https://github.com/psf/requests/blob/master/HISTORY.md#2160-2017-05-26) which was released in May 2017. Before that, a vendored package was included with `requests`. So either:
- You're using an ancient version of `requests`. There have been a few security-related releases since 2017 that make this a bad idea in general.
- You're using a newer version of `requests`, but somehow your setup is broken and you're not using a regular install of `urllib3`. I can't see how the `requests` library could have worked without it.

FYI, the PR is merged and I have released v2.5.1 with your change.

**Comment by jacopsd** [comment]
Tom

I see the point.

Indeed, my requests version is old: 2.13.0
I will update that.

Thank you for your help.

Regards
Davy

**Comment by whyscream** [comment]
Good luck, thanks for reporting.

**Comment by jacopsd** [comment]
Tom

Follow up:

Doc says:
mollie_client.setup_oauth_authorization_response(authorization_response)
# The token will be stored via your `set_token` method for future use. Expired tokens will be refreshed by the client automatically.
# Now You can query the API:
mollie_client.organizations.get('me')

Indeed, organisations.get(‘me’) works fine now.


But to create a payment, we need the profile ID.
To get the profile ID, we need to call “mollie_client.profiles.get('me’)”  or something similar?

This results in error;

	“This API endpoint is only available with an API key and cannot be accessed with an OAuth access token.”


How to resolve this?

Thx
Davy

**Comment by whyscream** [comment]
>  But to create a payment, we need the profile ID.
> To get the profile ID, we need to call “mollie_client.profiles.get('me’)”  or something similar?

You can retrieve the profile ID from the mollie dashboard. It's not something that can be retrieved through the API.

**Comment by jacopsd** [comment]
Tom

Op het dashboard?

Ik zie dit bij profielen. Wat is dan de profile ID?



Groeten
Davy

**Comment by whyscream** [comment]
You can find the API keys in your dashboard under Developers => API keys:

mollie-dashboard1

After completing the account setup:

mollie-dashboard2

When your application only needs to handle simple payments, you can probable implement the API key authentication, there will be no need for the more complex OAuth setup.

**Pull request merged**
